version: '3.7'

volumes:
  volume-mysql:


services:

  arcturus:
    container_name: arcturus
    build:
      context: Arcturus
    entrypoint: ["/bin/sh","/app/Scripts/build.sh"]
    restart: always
    volumes:
      - ./Arcturus:/app
    depends_on:
      - mysql
    ports:
      - 13000:3000
      - 13001:3001
      - 13002:2096
    networks:
      nitro:

  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=arcturus_root_pw
      - MYSQL_USER=arcturus_user
      - MYSQL_PASSWORD=arcturus_pw
      - MYSQL_DATABASE=arcturus
    volumes:
      - volume-mysql:/var/lib/mysql
      - ./Mysql/conf.d:/etc/mysql/conf.d
      - ./Arcturus/Database:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306
    networks:
      nitro:

networks:
  nitro:
