version: '3.7'

volumes:
  volume-mysql:


services:

  arcturus:
    container_name: arcturus
    build:
      context: Arcturus
    volumes:
      - ./Arcturus-Community:/app
    depends_on:
      - mysql
    networks:
      nitro:

  mysql:
    container_name: mysql
    image: library/mariadb:10.5.13
    env_file:
      - Mysql/.env
    ports:
      - "13306:3306"
    volumes:
      - volume-mysql:/var/lib/mysql
      - ./Mysql/conf.d:/etc/mysql/conf.d
    networks:
      nitro:

networks:
  nitro:
