version: '3.7'

volumes:
  volume-mysql:


services:

  arcturus:
    container_name: arcturus
    build:
      context: emulator
    entrypoint: ["/bin/sh","/app/scripts/build.sh"]
    volumes:
      - ./emulator/:/app/
    depends_on:
      - mysql
    ports:
      - 13000:3000
      - 13001:3001
      - 13002:2096
    networks:
      nitro:

  nitro:
    container_name: nitro
    build:
      context: nitro
    entrypoint: ["/bin/sh","/app/scripts/build.sh"]
    volumes:
      - ./nitro/:/app/
    ports:
      - 80:80
    networks:
      nitro:

  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=arcturus_root_pw
      - MYSQL_USER=arcturus_user
      - MYSQL_PASSWORD=arcturus_pw
      - MYSQL_DATABASE=arcturus
    volumes:
      - volume-mysql:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/dumps:/docker-entrypoint-initdb.d
    ports:
      - 13306:3306
    networks:
      nitro:

networks:
  nitro:
